online_shop/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

online_shop/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('config/', views.stripe_config, name='stripe-config'),
    path('buy/<int:pk>/', views.create_item_checkout_session,
         name='buy'),
    path('orders/buy/<int:pk>/', views.create_order_checkout_session,
         name='order_buy'),
    path('success/', views.SuccessView.as_view(), name='success-view'),
    path('cancelled/', views.CancelledView.as_view(), name='cancelled-view'),
    path('item/', views.ItemListView.as_view(), name='items_list'),
    path('item/<int:pk>/', views.ItemDetailView.as_view(), name='item_detail'),
    path('orders/', views.OrderListView.as_view(), name='orders_list'),
    path('orders/<int:pk>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('orders/create/', views.OrderCreateView.as_view(), name='order_create'),
]

online_shop/main/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    CURRENCY_CHOICES = (
        ('rub', 'Russian Ruble'),
        ('usd', 'American Dollar'),
    )
    currency = models.CharField(max_length=3, choices=CURRENCY_CHOICES, default=CURRENCY_CHOICES[0][0],
                                verbose_name='Currency')

    def __str__(self):
        return self.username


class Item(models.Model):
    name = models.CharField(max_length=50, verbose_name='Name')
    description = models.TextField(verbose_name='Description')
    price = models.IntegerField(default=0, verbose_name='Price')
    stripe_price = models.CharField(max_length=250, verbose_name="Stripe Price's ID")

    def __str__(self):
        return self.name


class Order(models.Model):
    items = models.ManyToManyField(Item, verbose_name='Items')

online_shop/main/forms.py
from django import forms

from .models import Order, Item


class OrderForm(forms.ModelForm):
    items = forms.ModelMultipleChoiceField(
        queryset=Item.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = Order
        fields = ('items', )

online_shop/main/views.py
import stripe
from django.conf import settings
from django.http.response import JsonResponse
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DetailView, ListView, CreateView
from django.views.generic.base import TemplateView

from .forms import OrderForm
from .models import Item, Order


class HomeView(TemplateView):
    template_name = 'home.html'


class ItemListView(ListView):
    model = Item
    template_name = 'items/items_list.html'
    context_object_name = 'items_list'


class ItemDetailView(DetailView):
    model = Item
    template_name = 'items/item_detail.html'
    context_object_name = 'item'


class OrderListView(ListView):
    model = Order
    template_name = 'orders/orders_list.html'
    context_object_name = 'orders_list'


class OrderDetailView(DetailView):
    model = Order
    template_name = 'orders/order_detail.html'
    context_object_name = 'order'


class OrderCreateView(CreateView):
    model = Order
    template_name = 'orders/order_create.html'
    form_class = OrderForm
    success_url = reverse_lazy('orders_list')


class SuccessView(TemplateView):
    template_name = 'stripe_templates/success.html'


class CancelledView(TemplateView):
    template_name = 'stripe_templates/cancelled.html'


@csrf_exempt
def stripe_config(request):
    if request.method == 'GET':
        stripe_config = {'publicKey': settings.STRIPE_PUBLISHABLE_KEY}
        return JsonResponse(stripe_config, safe=False)


@csrf_exempt
def create_item_checkout_session(request, pk):
    try:
        item = Item.objects.get(id=pk)
        domain_url = 'http://127.0.0.1:8000/'
        stripe.api_key = settings.STRIPE_SECRET_KEY

        checkout_session = stripe.checkout.Session.create(
            success_url=domain_url + 'success?session_id={CHECKOUT_SESSION_ID}',
            cancel_url=domain_url + 'cancelled/',
            payment_method_types=['card'],
            mode='payment',
            currency=request.user.currency,
            line_items=[
                {
                    'price': item.stripe_price,
                    'quantity': 1,
                }

            ],
        )

        return JsonResponse({'sessionId': checkout_session['id']})

    except Exception as e:
        return JsonResponse({'error': str(e)})



@csrf_exempt
def create_order_checkout_session(request, pk):
    try:
        order_items = Order.objects.get(id=pk).items.all()
        domain_url = 'http://127.0.0.1:8000/'
        stripe.api_key = settings.STRIPE_SECRET_KEY
        line_items_list = []

        for item in order_items:
            line_items_list.append(
                {
                    'price': item.stripe_price,
                    'quantity': 1
                }
            )

        checkout_session = stripe.checkout.Session.create(
            success_url=domain_url + 'success?session_id={CHECKOUT_SESSION_ID}',
            cancel_url=domain_url + 'cancelled/',
            payment_method_types=['card'],
            mode='payment',
            currency=request.user.currency,
            line_items=line_items_list,
        )

        return JsonResponse({'sessionId': checkout_session['id']})

    except Exception as e:
        return JsonResponse({'error': str(e)})

online_shop/main/templates/home.html
{% extends "layout/base.html" %}

{% block content %}
  <h1>Hello, welcome to our online store!</h1>
  <a href="{% url 'items_list' %}" class="btn btn-primary">All Items</a>
{% endblock %}

online_shop/main/templates/items/item_detail.html
{% extends 'layout/base.html' %}

{% block script %}
    <script type="text/javascript">
        // Get Stripe publishable key
        fetch("/config/")
        .then((result) => { return result.json(); })
        .then((data) => {
          // Initialize Stripe.js
          const stripe = Stripe(data.publicKey);

          // new
          // Event handler
          document.querySelector("#submitBtn").addEventListener("click", () => {
            // Get Checkout Session ID
            fetch("{% url 'buy' item.id %}")
            .then((result) => { return result.json(); })
            .then((data) => {
              console.log(data);
              // Redirect to Stripe Checkout
              return stripe.redirectToCheckout({sessionId: data.sessionId})
            })
            .then((res) => {
              console.log(res);
            });
          });
        });
    </script>
{% endblock %}

{% block content %}
  <h2>Information about {{ item.name }}</h2>
  <p>Name: {{ item.name }}</p>
  <p>Description: {{ item.description }}</p>
  <p>Price: {{ item.price }}</p>
  <p>Your currency of payment (if you want to change the currency - go to your profile): {{ user.get_currency_display }}</p>
  <button class="btn btn-primary" id="submitBtn">Buy!</button>
{% endblock %}

online_shop/main/templates/items/items_list.html
{% extends "layout/base.html" %}

{% block content %}
  <h2>Information about all items</h2>
  {% if items_list %}
    {% for item in items_list %}
      <p><a href="{% url 'item_detail' pk=item.id %}">Name: {{ item.name }}</a></p>
      <p>Description: {{ item.description }}</p>
      <p>Price: {{ item.price }}</p>
    {% endfor %}
  {% else %}
    <p>There are currently no items on the site.</p>
  {% endif %}
{% endblock %}

online_shop/main/templates/layout/base.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script defer src="https://use.fontawesome.com/releases/v6.4.0/js/all.js"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <title>{% block title %}Django + Stripe Shop{% endblock %}</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='slim' %}
    {% block script %}<script></script>{% endblock %}
</head>
<body class="container-fluid">
    <header class="mb-4">
        <h1 class="display-1 text-center">Django + Stripe Store</h1>
    </header>
    <div class="row">
        <ul class="col nav justify-content-end border">
            <li class="nav-item"><a class="nav-link" href="{% url 'home' %}">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'items_list' %}">All Items</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'orders_list' %}">All Your Orders</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'order_create' %}">Create Order</a></li>

        </ul>
    </div>
    <section class="col border py-2">
        {% block content %}
        {% endblock %}
    </section>
    <footer class="mt-3">
        <p class="text-right font-italic">&copy; shoksdev</p>
    </footer>
</body>
</html>

online_shop/main/templates/orders/order_create.html
{% extends "layout/base.html" %}
{% load bootstrap4 %}

{% block title %}Create Order{% endblock %}

{% block content %}
    <h2>Create Order</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons submit='Create' %}{% endbuttons %}
    </form>
{% endblock %}

online_shop/main/templates/orders/order_detail.html
{% extends 'layout/base.html' %}

{% block script %}
    <script type="text/javascript">
        // Get Stripe publishable key
        fetch("/config/")
        .then((result) => { return result.json(); })
        .then((data) => {
          // Initialize Stripe.js
          const stripe = Stripe(data.publicKey);

          // new
          // Event handler
          document.querySelector("#submitBtn").addEventListener("click", () => {
            // Get Checkout Session ID
            fetch("{% url 'order_buy' order.id %}")
            .then((result) => { return result.json(); })
            .then((data) => {
              console.log(data);
              // Redirect to Stripe Checkout
              return stripe.redirectToCheckout({sessionId: data.sessionId})
            })
            .then((res) => {
              console.log(res);
            });
          });
        });
    </script>
{% endblock %}

{% block content %}
  <h2>Order number {{ order.id }}</h2>
  <p>Items in order:</p>
  <p>-------------------------------------------</p>
  {% for item in order.items.all %}
      <p>Name: <a href="{% url 'item_detail' pk=item.id %}">{{ item.name }}</a></p>
      <p>Description: {{ item.description }}</p>
      <p>Price: {{ item.price }}</p>
      <p>-------------------------------------------</p>
  {% endfor %}
  <button class="btn btn-primary" id="submitBtn">Buy!</button>
{% endblock %}

online_shop/main/templates/orders/orders_list.html
{% extends "layout/base.html" %}

{% block content %}
  <h2>Information about all your orders</h2>
  {% if orders_list %}
    {% for order in orders_list %}
        <p><a href="{% url 'order_detail' pk=order.id %}">Order's ID: {{ order.id }}</a></p>
        <p>Items in order:</p>
        <p>-------------------------------------------</p>
        {% for item in order.items.all %}
            <p>Name: <a href="{% url 'item_detail' pk=item.id %}">{{ item.name }}</a></p>
            <p>Description: {{ item.description }}</p>
            <p>Price: {{ item.price }}</p>
            <p>-------------------------------------------</p>
        {% endfor %}
        <p>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</p>
    {% endfor %}
  {% else %}
    <p>There are currently no orders on your account.</p>
  {% endif %}
{% endblock %}

online_shop/main/templates/stripe_templates/cancelled.html
{% extends "layout/base.html" %}

{% block content %}
  <h2>Your payment was cancelled.</h2>
{% endblock %}

online_shop/main/templates/stripe_templates/success.html
{% extends "layout/base.html" %}

{% block content %}
  <h2>Your payment succeeded.</h2>
{% endblock %}